objects/Airport__c/Airport__c.object-meta.xml
<CustomObject>
    <label>Airport</label>
    <nameField>
        <label>Airport Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Airports</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Airport__c/fields/IATACode__c.field-meta.xml
<CustomField>
    <fullName>IATACode__c</fullName>
    <label>IATA code</label>
    <length>3</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

classes/AirportSelector.cls
public with sharing class AirportSelector {
    public static AirportSelector getInstance(){
        return new AirportSelector();
    }

    public List<Airport__c> getAirportByIATACode(String IATACode){
        return [SELECT Id, IATACode__c, Location__c  FROM Airport__c WHERE IATACode__c =: IATACode];
    }

    public List<Airport__c> getAirportsOrderByIATACode(){
        return [SELECT Id, Name, IATACode__c FROM Airport__c ORDER BY IATACode__c];
    }
}